function TrailingZero(n){
    var factorial=1
    for(i=1;i<=n;i++){
        factorial=factorial*i
    }
    return factorial;
}
console.log(TrailingZero(1));
console.log(TrailingZero(2));
console.log(TrailingZero(3));
console.log(TrailingZero(4));
console.log(TrailingZero(5));
console.log(TrailingZero(6));
console.log(TrailingZero(7));
console.log(TrailingZero(8));
console.log(TrailingZero(9));
console.log(TrailingZero(10));
console.log(TrailingZero(11))
console.log(TrailingZero(12))
console.log(TrailingZero(13))
console.log(TrailingZero(14))
console.log(TrailingZero(15))
console.log(TrailingZero(16))
console.log(TrailingZero(17))
console.log(TrailingZero(18))
console.log(TrailingZero(19))
console.log(TrailingZero(20))
console.log(TrailingZero(125*5))




